routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::prefix('admin-tickets-managment')->namespace('Admin')->name('admin.')->group( function ()
{
    Route::resource('tickets', 'TicketsController');
});

Route::prefix('admin-comments-managment')->namespace('Admin')->name('admin.')->group( function ()
{
    Route::post('/commentsCreated/{ticket}', 'CommentsController@newComment')->name('commentsCreated');
});

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Ticket extends Model
{
    use Notifiable;
    protected $fillable =
    [
        'title',
        'content',
        'slug',
        'status',
    ];

    public function comments()
    {
        return $this->hasMany('App\Models\Comment','post_id');
    }


    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Admin/TicketsController.php
<?php

namespace App\Http\Controllers\Admin; //inseriti tu
use App\Http\Controllers\Controller; //inseriti tu


use App\Http\Requests\TicketsFormRequest;
use App\Models\Ticket;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class TicketsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tickets = Ticket::all();
        return view('ticket.index',compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ticket.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TicketsFormRequest $request)
    {

        try
        {
            DB::beginTransaction();

                $ticketData =
                [
                    'title' => $request->title,
                    'content' => $request->content,
                    'slug'   => uniqId(),
                ];

                //$insert_data = $request->except(['_token']); //entrambe valide
                $newTicket = Ticket::create($ticketData);

            DB::commit();

                session()->flash('success','tickets creato con successo L\'id è: '.$newTicket->slug);
                return redirect()->route('admin.tickets.index');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Non è stato possibile creare il ticket'
            ];
            session()->flash('error',$errors);
            return redirect()->route('admin.tickets.create');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        try
        {
            DB::beginTransaction();

                $ticket->load('comments');

            DB::commit();

                return view('ticket.show',compact('ticket'));
        }
        catch(\Exception $e)
        {

            $errors =
            [
                'error_message' => 'Ticket non trovato'
            ];

            session()->flash('error',$errors);
            return redirect()->route('admin.ticket.index');

        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {

        if(!$ticket)
        {
            $errors =
            [
                'error_message' => 'Ticket non trovato'
            ];

            session()->flash('error',$errors);
            return redirect()->route('admin.ticket.index');
        }

        return view('ticket.edit',compact('ticket'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TicketsFormRequest $request, Ticket $ticket)
    {

        try
        {
            DB::beginTransaction();

                if($request->status != null)
                {
                    $status = 0;
                }
                else
                {
                    $status = 1;
                }

                $updated = $ticket->update(
                [
                    'title'      =>     $request->title,
                    'content'    =>     $request->content,
                    'status'     =>     $status,
                ]);


            DB::commit();

                session()->flash('success',('Ticket mofificato con successo'));
                return redirect()->route('admin.tickets.index');
        }
        catch(\Exception $e)
        {

            $errors =
            [
                'error_message' => 'Errore nella modifica del ticket',
            ];

            session()->flash('error',$errors);
            return redirect()->route('admin.tickets.index');

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {

        try
        {
            DB::beginTransaction();


                $deleted = $ticket->delete();

            DB::commit();

                session()->flash('success',('Ticket cancellato con successo'));
                return redirect()->route('admin.tickets.index');

        }
        catch(\Exception $e)
        {

            $errors =
            [
                'error_message' => 'Errore nella rimozione del ticket',
            ];

            session()->flash('error',$errors);
            return redirect()->route('admin.tickets.index');

        }

    }
}

resources/views/ticket/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container col-md-8 col-md-offset-2">


    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @include('components.message')


    <div class="mt-5 card">
        <div class="card-header ">
            <h5 class="float-left">Create a ticket</h5>
            <div class="clearfix"></div>
        </div>
        <div class="mt-2 card-body">
            <form method="post" action="{{route('admin.tickets.store')}}">
                @csrf
                <fieldset>
                    <div class="form-group">
                        <label for="title" class="col-lg-2 control-label">Title</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" id="title" placeholder="Title" name="title" value="{{old('title') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="content" class="col-lg-2 control-label">Content</label>
                        <div class="col-lg-10">
                            <textarea class="form-control" rows="3" id="content" name="content" value="{{old('content') }}"></textarea>
                            <span class="help-block">Feel free to ask us any question.</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button class="btn btn-default">Cancel</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/ticket/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container col-md-8 col-md-offset-2">


        @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
        @endif
        @include('components.message')


        <div class="card mt-5">
            <div class="card-header ">
                <h5 class="float-left">Edit ticket</h5>
                <div class="clearfix"></div>
            </div>
            <div class="card-body mt-2">
                <form method="post" action="{{route('admin.tickets.update',$ticket)}}">
                    @method('patch')
                    @csrf

                    <fieldset>
                        <div class="form-group">
                            <label for="title" class="col-lg-2 control-label">Title</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="title" placeholder="Title" name="title" value="{{ $ticket->title }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="content" class="col-lg-2 control-label">Content</label>
                            <div class="col-lg-10">
                                <textarea class="form-control" rows="3" id="content" name="content">{{ $ticket->content }}</textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>
                                <input type="checkbox" name="status" {{ $ticket->status ? "" : "checked"}} > Close this ticket?
                            </label>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-10 col-lg-offset-2">
                                <button class="btn btn-default">Cancel</button>
                                <button type="submit" class="btn btn-primary">Update</button>
							</div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/ticket/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container col-md-8 col-md-offset-2 t-5">

        @include('components.message')

        <div class="card">
            <div class="card-header ">
                <h5 class="float-left">Tickets</h5>
                <div class="clearfix"></div>
            </div>
            <div class="card-body mt-2">
                @if ($tickets->isEmpty())
                    <p> There is no ticket.</p>
                @else
                    <table class="table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($tickets as $ticket)
                            <tr>
                                <td>{{ $ticket->id }} </td>
                                <td> <a href="{{route('admin.tickets.show', $ticket)}}"> {{ $ticket->title }} </a> </td>

                                <td>{{ $ticket->status ? 'Pending' : 'Answered' }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/ticket/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container col-md-8 col-md-offset-2 mt-5">
    <div class="card">
        <div class="card-header ">
            <h5 class="float-left">{{ $ticket->title }}</h5>
            <div class="clearfix"></div>
        </div>
        <div class="card-body">
            <p> <strong>Status</strong>: {{ $ticket->status ? 'Pending' : 'Answered' }}</p>
            <p> {{ $ticket->content }} </p>
            @foreach($ticket->comments as $comment)
                <div class="card mt-3">
                    <div class="card-body">
                        {{ $comment->content }}
                    </div>
                </div>
            @endforeach

            <a href="{{route('admin.tickets.edit', $ticket)}}" class="btn btn-info">Edit</a>

            <form  style="display: inline-block" method="POST" action="{{route('admin.tickets.destroy', $ticket )}}">
                @csrf
                @method('delete')

                <button type="submit"  class="btn btn-warning"> Delete </button>

            </form>

        </div>
    </div>


    <div class="card mt-3">
        <form method="post" action="{{route('admin.commentsCreated',$ticket)}}">
            @csrf

            @include('components.message')
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


            <fieldset>
                <legend class="ml-3">Reply</legend>


                <div class="form-group">
                    <div class="col-lg-12">
                        <textarea class="form-control" rows="3" id="content" name="content"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                        <button type="reset" class="btn btn-default">Cancel</button>
                        <button type="submit" class="btn btn-primary">Post</button>
                    </div>
                </div>
            </fieldset>

        </form>
    </div>

</div>
@endsection